QALD9: Portuguese string correction
ag-sc/QALD pull request #29
Opened 2022-07-01 12:43 UTC by nikit91

As mentioned in https://github.com/ag-sc/QALD/issues/22, the Portuguese question strings are replaced with the strings mentioned in the [spreadsheet](https://docs.google.com/spreadsheets/d/1NMo4bS49eseQt47MH4cA5GoajZySt2gNOzmO1eoOS3I/edit#gid=550865483). 

The replaced string is the last (column-wise) non-empty value present for each row.

2022-07-01 14:12 UTC, RicardoUsbeck commented
@arademaker please check the pull request.

2022-07-28 15:01 UTC, RicardoUsbeck commented
Ping @arademaker

2022-07-29 17:14 UTC, arademaker commented
I will take a look until begin next week

2022-08-08 14:09 UTC, arademaker commented on 9/data/qald-9-test-multilingual.json
> +      "string" : "Liste para mim os sítios web das companhias com mais de 500000 empregados.",
This is a European Portuguese translation. In Brazil we would say 

> Liste para mim os sites das companhias com mais de 50 mil funcionários.

2022-08-08 14:10 UTC, arademaker commented on 9/data/qald-9-test-multilingual.json
> +      "string" : "Leve-me às trilhas do Grand Canyon em que não há perigo de inundações.",
acho que não seria "leve-me" mas "mostre-me"

2022-08-08 14:25 UTC, arademaker requested changes
this is a partical review of some PT translations. My suggestions would be to accept this PR and than I can make a new PR with more reviews, does it work?

2022-08-08 14:25 UTC, arademaker commented on 9/data/qald-9-test-multilingual.json
> +      "string" : "Quais pontes são do mesmo tipo da ponte de Manhattan?",
quais pontes são do mesmo tipo que a ponte de Manhattan?

2022-08-08 14:25 UTC, arademaker commented on 9/data/qald-9-test-multilingual.json
> +      "string" : "Quem chamava Rodzilla?",
quem era chamado Rodzilla?

2022-08-08 14:25 UTC, arademaker commented on 9/data/qald-9-test-multilingual.json
> +      "string" : "Em qual estúdio os BEatles gravaram o primeiro albúm?",
Beatles (see capitalization)

2022-08-08 14:25 UTC, arademaker commented on 9/data/qald-9-test-multilingual.json
> +      "string" : "Qual o romancista que escreveu as Crônicas de gelo e fogo?",
Crônicas de Gelo e Fogo? (capitalization)

2022-08-08 14:25 UTC, arademaker commented on 9/data/qald-9-test-multilingual.json
> +      "string" : "Qual o nome da famosa batalha em 1863 que ocorre em Santo Antônio?",
Qual o nome da famosa batalha que ocorre em Santo Antônio em 1863?

2022-08-08 14:25 UTC, arademaker commented on 9/data/qald-9-test-multilingual.json
> +      "string" : "O nome da esposa do presidente Obama se chamaMichelle?",
O nome da esposa do presidente Obama é Michelle?

2022-08-08 14:25 UTC, arademaker commented on 9/data/qald-9-test-multilingual.json
> +      "string" : "O quão grande é o diâmetro da Terra?",
Qual o tamanho do diâmetro da Terra?

2022-08-08 14:25 UTC, arademaker commented on 9/data/qald-9-test-multilingual.json
> +      "string" : "Quando o paraguay proclamou a independência?",
Paraguay (capitalization)

2022-08-08 14:25 UTC, arademaker commented on 9/data/qald-9-test-multilingual.json
> +      "string" : "Qual o nome da universidade que a esposa so Obama estudou?",
Qual o nome da universidade que a esposa **de** Obama estudou?

2022-08-08 14:25 UTC, arademaker commented on 9/data/qald-9-test-multilingual.json
> +      "string" : "Qual das filhas da British earls morreu no mesmo local de nascimento?",
Quais filhas de condes britânicos morreram no mesmo lugar em que nasceram?

2022-08-09 13:09 UTC, nikit91 commented
@arademaker if you can add your corrections to this [sheet](https://docs.google.com/spreadsheets/d/1NMo4bS49eseQt47MH4cA5GoajZySt2gNOzmO1eoOS3I/edit#gid=550865483) in a new column, then I can quickly update them in this PR. I have scripts written that will update the queries using the latest correction for each of these entries.

2022-08-09 13:11 UTC, arademaker commented
I would prefer to work in the text file directly, if possible. I am much more efficient with my emacs than using Google spreadsheet! ;-)

2022-08-09 13:13 UTC, arademaker commented
Besides that, having PRs accepted is a way to formally collaborate in a public repository, right? ;-)

2022-08-09 13:18 UTC, nikit91 commented
well, fair point. I guess then @RicardoUsbeck could accept this PR and afterwards you (@arademaker) can raise a separate PR with corrections :)

2022-08-09 19:46 UTC, RicardoUsbeck commented
I am actually not sure what is happening here. If I just click 'resolve' on all comments from @arademaker shouldn't that be it? Why would he need to raise another PR, @nikit91 ?

2022-08-09 19:50 UTC, arademaker commented
I made comments, no updates on the files. Someone need to apply my comments changing this PR (new commit) and accepting it. 

I do see more corrections to make. So I will open a new PR to that after this PR is accepted. 

Alternatively, ignore my comments. Accept this PR and I later make a new PR to fix directly the files with the erros I already mentioned in the comments and new ones that I know to exist.

2022-08-09 19:56 UTC, RicardoUsbeck commented
Thanks for the super fast reply. I will accept this PR as is and leave it to your emacs magic to create a new PR.

2022-08-09 19:56 UTC, merged